### ISSUE TITLE
Error Initializing API Project - Reason: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim-tooling#510] opened 2020-10-21 05:16 UTC
**Description:**

When using [1] to initialize an API Project using apictl init command, the following error message was printed.
```
apictl: Error initializing project Reason: yaml: control characters are not allowed
Exit status 1
```
It is possible to import these APIs using the publisher UI and publish them to the devportal.

**Suggested Labels:**
Import-third-party-APIs

**Affected Product Version:**
apictl-3.2.0

**OS, DB, other environment details and versions:**   
OS: Ubuntu 20.04.1 LTS (64-bit) 

**Steps to reproduce:**
1. Use [1] as the --oas parameter value and initialize an API project using apictl. This would result in the error message.

![control_characters_error](https://user-images.githubusercontent.com/30455603/96676134-44770f00-138a-11eb-9428-a7f8c977288c.png)

[1] https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/docusign.net/v2/swagger.yaml

**Comment by npamudika** [comment] 2021-02-15 12:35
Couldn't find the swagger file in the provided link to try reproducing the issue. Could you please attach a sample swagger file to the git issue?

**Comment by npamudika** [comment] 2021-03-12 09:17
Closing this as unable to reproduce the issue locally.

**Closed by npamudika** 2021-03-12 09:17 UTC
Labels: 4.0.0, Affected/3.2.0, Priority/High, Type/Bug
