### ISSUE TITLE
'apictl change registry' doesn't validate Dockerhub credentials

### ISSUE THREAD

**Issue by lahirus** [wso2/product-apim-tooling#289] opened 2020-04-28 14:53 UTC
**Description:**
apictl change registry doesn't validate Dockerhub credentials

**Affected Product Version:**
APICTL used with MGW 3.1.x. (April 28, 2020)

**OS, DB, other environment details and versions:**    
Ubuntu
**Steps to reproduce:**
Run 'apictl change registry'. Output:

$ apictl change registry
Choose registry type:
1: Docker Hub (Or others, quay.io, HTTPS registry)
2: Amazon ECR
3: GCR
4: HTTP Private Registry
Choose a number: 1: 1
Enter repository name (docker.io/john | quay.io/mark | 10.100.5.225:5000/jennifer): hub.docker.com/lahirus
Enter username: lahirus
Enter password:

Repository: hub.docker.com/lahirus
Username  : lahirus
Confirm configurations: Y: Y
configmap/docker-registry-config configured
secret/docker-registry-credentials configured

**Related Issues:**

**Comment by renuka-fernando** [comment] 2020-10-26 13:22
hi @lahirus 

It should be the same inputs as in the apictl installation [1]. So for your case it should be as follows.

Enter repository name: **docker.io/lahirus**
Enter username: **lahirus**

For other docker registry types: [2] Working with Docker Registries.

[1] API Operator 1.1.0 docs: https://github.com/wso2/k8s-api-operator/blob/v1.1.0/docs/GettingStarted/quick-start-guide.md#step-3-install-api-operator
[2] API Operator 1.1.0 docs: https://github.com/wso2/k8s-api-operator/tree/v1.1.0/docs

**Comment by npamudika** [comment] 2020-10-27 06:36
Closing the issue as the issue is addressed in the previous comment.

**Closed by npamudika** 2020-10-27 06:36 UTC
Labels: Affected/3.1.0, Priority/Normal, Type/Bug
