### ISSUE TITLE
Login failed to apim after adding an environment with --apim and --mi flags

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-apim-tooling#655] opened 2021-03-12 14:19 UTC
**Description:**
Please follow the below steps to reproduce the issue.
```bash
indika@indikas:~/apim4-alpha/apictl-4.0.0-alpha2-linux-x64/apictl$ ./apictl add env local --apim  https://apim.com:9443 --mi https://localhost:9164
Default token endpoint 'https://apim.com:9443/oauth2/token' is added as the token endpoint 
Successfully added environment 'local'
indika@indikas:~/apim4-alpha/apictl-4.0.0-alpha2-linux-x64/apictl$ 
indika@indikas:~/apim4-alpha/apictl-4.0.0-alpha2-linux-x64/apictl$ ./apictl get envs
NAME                API MANAGER ENDPOINT    REGISTRATION ENDPOINT   TOKEN ENDPOINT                       PUBLISHER ENDPOINT   DEVPORTAL ENDPOINT   ADMIN ENDPOINT      MI MANAGEMENT ENDPOINT
local               https://apim.com:9443                           https://apim.com:9443/oauth2/token                                                                 https://localhost:9164
indika@indikas:~/apim4-alpha/apictl-4.0.0-alpha2-linux-x64/apictl$ 
indika@indikas:~/apim4-alpha/apictl-4.0.0-alpha2-linux-x64/apictl$ ./apictl login local
Username:admin
Password:
apictl: Error in connecting. Reason: Post "https://apim.com:9443/client-registration/v0.17/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Exit status 1
```

If the token endpoint is not defined, it is by default added as `https://apim.com:9443/oauth2/token`. Therefore, the login failed. The only way to get it to work is to add the `--token` endpoint with the above flags. Is there a specific reason to add these endpoints with some bogus domain name? I feel it is breaking the first user experience.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
 apictl-4.0.0-alpha2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment] 2021-03-15 07:54
Hi Indika,

It doesn't pick a random domain name, instead it gets the domain name of the --apim flags value when defining the environment if the --token flag is not defined. This is the expected behaviour, as when a separate --token flag is not provided, it will consider the APIM serer as an all-in-one pack and add the token endpoint accordingly.

If you want to have a different token endpoint, you need to provide it when adding the environment.

In your case, you need to provide --apim with "https://localhost:9443" value. Please let us know the status after trying this.

Thanks,
Naduni

**Comment by npamudika** [comment] 2021-03-23 15:48
Closing the issue as answered the concerns. This is not a bug and the expected behaviour.

**Closed by npamudika** 2021-03-23 15:48 UTC
Labels: 4.0.0, Priority/High, Resolution/Answered, Type/Question
