### ISSUE TITLE
Mac doesn't trust the developer of apictl

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim-tooling#476] opened 2020-09-04 11:40 UTC
**Description:**
Mac doesn't trust the developer of apictl.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by 1akshitha** [comment] 2021-02-17 04:33
Closing the issue since it is not reproducible in the latest mac OS versions.

**Closed by 1akshitha** 2021-02-17 04:33 UTC
Labels: 4.0.0, Affected/3.0.0, Priority/Normal, Type/Improvement

**Comment by 1akshitha** [comment] 2021-08-19 18:26
This is due to the Mac's security and Privacy policy issues. You can trust the executable binary by following the macOS user guide to **See Open an app by overriding security settings**.  You can follow the below steps to trust the developer.

<img width="529" alt="Screenshot 2021-08-19 at 11 55 46 PM" src="https://user-images.githubusercontent.com/47380453/130123938-7228fdbb-a04a-4f4a-adfd-6dcf4e39af4c.png">
