### ISSUE TITLE
Error Initializing API Project which has a Tab Character in the Definition

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim-tooling#507] opened 2020-10-20 10:33 UTC
**Description:**

When using [1] to initialize an API Project using ```apictl init``` command, the following error message was printed.
```
apictl: Error initializing project Reason: yaml: line 672: found a tab character where an indentation space is expected
Exit status 1
```
There is a tab character in line 672. But it is possible to import this API using the publisher UI and publish to the devportal.

**Suggested Labels:**
Import-third-party-APIs

**Affected Product Version:**
apictl-3.2.0

**OS, DB, other environment details and versions:**    
OS: Ubuntu 20.04.1 LTS (64-bit)

**Steps to reproduce:**
1. Use [1] as the --oas parameter value and initialize an API project using apictl. This would result in the error message.
![tab-issue](https://user-images.githubusercontent.com/30455603/96574837-97e74f80-12ed-11eb-9fbf-c82d2a84165f.png)

[1] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/adyen.com/CheckoutService/37/openapi.yaml

**Comment by npamudika** [comment] 2020-11-06 09:48
Hi @hisanhunais,

This error occurs as you have a tab character in your definition file and yaml forbids it. In order to overcome the issue, please ensure that there are no tabs in the yaml file.

You can remove the white spaces and replace them with the space character or please use an editor which visualizes the white spaces and tabs and replace them with space characters. Like wise you can convert tabs to space characters and ensure that the indentation is correct prior executing the init command against the yaml file.

Since this is not a bug, closing the issue.

**Closed by npamudika** 2020-11-06 09:48 UTC
Labels: Affected/3.2.0, Next Release - 4.x, Priority/High, Type/Bug
