### ISSUE TITLE
Default version option is disabled when importing the API using APIMCLI 2.0.8.

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim-tooling#399] opened 2020-07-09 07:22 UTC
**Description:**
We have created an API by enabling the "Make this the default version" as true. Then we exported the API and imported into another environment and we were able to observe that the enabled option is disabled in the imported API.

**Suggested Labels:**
APIMCLI 2.0.8

**Affected Product Version:**
APIM 2.6.0

**Steps to reproduce:**

- Create an API by enabling the "Make this the default version" option in Manage tab.

- Then export the API using APIMCLI 2.0.8

- Then import into another environment.

- Then check in the manage tab of the API.

**Comment by npamudika** [comment] 2020-07-10 07:29
This is the expected behaviour and this has been done to overcome https://github.com/wso2/product-apim/issues/3610

**Comment by npamudika** [comment] 2020-07-10 07:30
Since this is not an issue, I am resolving this, please feel free to comment if you need any further clarifications regarding this.

**Closed** 2020-07-10 07:30 UTC
Labels: Affected/2.0.7, Resolution/Answered, Type/Bug
