### ISSUE TITLE
500 Internal error when importing app with subscriptions and changing owner

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim-tooling#751] opened 2021-05-20 11:10 UTC
**Description:**

```
[2021-05-20 16:36:11,183]  INFO - CommonUtil Creation of folder is successful. Directory Name : peter-PizzaInnApp
[2021-05-20 16:36:11,233] ERROR - ApiMgtDAO Failed to add subscriber data 
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_E18: PUBLIC.AM_SUBSCRIPTION FOREIGN KEY(API_ID) REFERENCES PUBLIC.AM_API(API_ID) (0)"; SQL statement:
 INSERT INTO    AM_SUBSCRIPTION (TIER_ID,API_ID,APPLICATION_ID,SUB_STATUS,SUBS_CREATE_STATE,CREATED_BY,CREATED_TIME,    UPDATED_TIME, UUID, TIER_ID_PENDING)  VALUES (?,?,?,?,?,?,?,?,?,?) [23506-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:319) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:261) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.table.Table.fireConstraints(Table.java:1020) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.table.Table.fireAfterRow(Table.java:1038) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.dml.Insert.insertRows(Insert.java:194) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.dml.Insert.update(Insert.java:132) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:133) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.command.Command.executeUpdate(Command.java:267) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200) ~[h2_1.4.199.wso2v1.jar:?]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154) ~[h2_1.4.199.wso2v1.jar:?]
	at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[jdbc-pool_9.0.35.wso2v1.jar:?]
	at com.sun.proxy.$Proxy49.executeUpdate(Unknown Source) ~[?:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription_aroundBody230(ApiMgtDAO.java:5371) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription(ApiMgtDAO.java:5275) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription_aroundBody28(ApiMgtDAO.java:696) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addSubscription(ApiMgtDAO.java:689) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addSubscription_aroundBody102(APIConsumerImpl.java:2920) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.APIConsumerImpl.addSubscription(APIConsumerImpl.java:2888) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addSubscription_aroundBody0(UserAwareAPIConsumer.java:58) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIConsumer.addSubscription(UserAwareAPIConsumer.java:56) [org.wso2.carbon.apimgt.impl_9.0.174.jar:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.utils.ImportUtils.importSubscriptions(ImportUtils.java:197) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.applicationsImportPost(ApplicationsApiServiceImpl.java:243) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.store.v1.ApplicationsApi.applicationsImportPost(ApplicationsApi.java:470) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.34.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271) [cxf-rt-transports-http-3.3.7.jar:3.3.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107) [org.wso2.carbon.identity.context.rewrite.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.25.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102) [org.wso2.carbon.identity.auth.valve_1.4.25.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [tomcat_9.0.34.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126) [org.wso2.carbon.tomcat.ext_4.6.2.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat_9.0.34.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.34.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.34.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[2021-05-20 16:36:11,246] ERROR - GlobalThrowableMapper Failed to add subscriber data 

```
**Affected Product Version:**

API-M 4.0.0

**OS, DB, other environment details and versions:**    
Linux 19.04, H2 database, Java 1.11

**Steps to reproduce:**
1. Create an API in env1
2. Create an App in env1 for owner1 and subscribe to the API
2. Export API and import it to env2
3. Export App from env1
4. Import App to env2 with subscriptions and changing owner to owner2

**Comment by wasuradananjith** [comment] 2021-11-03 04:42
I tried to reproduce this issue. I followed the below steps.

1. Started two (2) APIM servers on ports 9443 and 9444. 
2. Added two (2) APIM servers as environments using apictl.
    ```
    apictl add env dev \
    --apim  https://localhost:9443 
    ```
    ```
    apictl add env production \
    --apim  https://localhost:9444 
    ```
3. Created a user named subscriber1 (with the Internal/subscriber role) in the APIM server in 9443 (dev)
4. Created a user named subscriber2 (with the Internal/subscriber role) in the APIM server in 9444 (production)
5. Created and deployed the PizzaShackAPI in dev env (as the admin user)
6. Created an application named TestApp1 in dev env (as subscriber1)
7. Exported the PizzaShackAPI as shown below.
    ![image](https://user-images.githubusercontent.com/25246848/140009967-369f1794-6c70-47d1-a10a-c827e0ddeb0f.png)
8. Exported the TestApp1 as shown below.
    ![image](https://user-images.githubusercontent.com/25246848/140010057-3b5591fb-e01f-43f9-9f2d-98fb0e873a01.png)
9. Logged into the Developer Portal of the production environment as subscriber2. (Otherwise changing the owner functionality won't work, unless the user is not registered as a subscriber as per the documentation in [1])
10. Imported the API to the production environment (as the admin user).
      ![image](https://user-images.githubusercontent.com/25246848/140010325-74def481-aaa6-43b5-a3dd-39c32843b9fc.png)
11. Imported the application to the production environment (as the admin user).
      ![image](https://user-images.githubusercontent.com/25246848/140010402-2c181a82-a9c7-4f64-8513-ff20070db180.png)
      Note that, the subscriptions are also imported correctly as shown below.
      ![image](https://user-images.githubusercontent.com/25246848/140010532-c8572832-b638-456c-bc35-8c32467286f7.png)
12. Logged into the Admin Portal and changed the owner of the application to subscriber2. No error occurred. (No login in the server as well)
      ![image](https://user-images.githubusercontent.com/25246848/140010619-b5bea9f6-502d-4bb4-a5d5-a369fdf5f897.png)
13. Logged into the Developer Portal of the production environment as the subscriber2 and checked the application. It is there with the subscriptions.
     ![image](https://user-images.githubusercontent.com/25246848/140010741-e577f44d-bfa2-4a14-81e5-d93a0f3aabf7.png)

Seems this issue has been already fixed. Are we good to close this or do we need to analyze this futher @dushaniw ?

[1] https://apim.docs.wso2.com/en/4.0.0/consume/manage-application/advanced-topics/changing-the-owner-of-an-application/#changing-the-owner-of-an-application

**Comment by wasuradananjith** [comment] 2022-02-28 08:56
Closing this, since this is not reproducible.

**Closed by wasuradananjith** 2022-02-28 08:56 UTC
Labels: Type/Bug, Priority/Highest, Affected/4.0.0, 4.1.0
